"""org settings fields

Revision ID: 3c7042ca2e0b
Revises: 6f17ff914f38
Create Date: 2025-12-22 13:37:00.183819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7042ca2e0b'
down_revision = '6f17ff914f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('logo_blob_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo_content_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('logo_content_type')
        batch_op.drop_column('logo_blob_name')
        batch_op.drop_column('contact_email')

    # ### end Alembic commands ###
