"""suspicious_ip_detection

Revision ID: ba938578c6f6
Revises: 9c40edd240de
Create Date: 2025-12-26 20:30:33.906758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba938578c6f6'
down_revision = '9c40edd240de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suspicious_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('window_started_at', sa.DateTime(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    with op.batch_alter_table('suspicious_ips', schema=None) as batch_op:
        batch_op.create_index('ix_suspicious_ips_blocked_until', ['blocked_until'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suspicious_ips', schema=None) as batch_op:
        batch_op.drop_index('ix_suspicious_ips_blocked_until')

    op.drop_table('suspicious_ips')
    # ### end Alembic commands ###
