"""user avatar fields

Revision ID: cdb2afe02d62
Revises: 3c7042ca2e0b
Create Date: 2025-12-22 15:11:06.480836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb2afe02d62'
down_revision = '3c7042ca2e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_blob_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('avatar_content_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_content_type')
        batch_op.drop_column('avatar_blob_name')

    # ### end Alembic commands ###
