"""login_activity_events

Revision ID: ce59a685b8e6
Revises: e80ea29bf39b
Create Date: 2025-12-26 19:49:27.537431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce59a685b8e6'
down_revision = 'e80ea29bf39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.create_index('ix_login_events_ip_created_at', ['ip_address', 'created_at'], unique=False)
        batch_op.create_index('ix_login_events_user_id_created_at', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.drop_index('ix_login_events_user_id_created_at')
        batch_op.drop_index('ix_login_events_ip_created_at')

    op.drop_table('login_events')
    # ### end Alembic commands ###
