"""add_session_version_for_logout_all_devices

Revision ID: d036b8f3059d
Revises: d9d1774a26cb
Create Date: 2026-01-01 13:21:29.741034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd036b8f3059d'
down_revision = 'd9d1774a26cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add column with server_default=1 for existing rows, then remove default
        batch_op.add_column(sa.Column('session_version', sa.Integer(), nullable=False, server_default='1'))
    
    # Remove server_default after initial data population
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('session_version', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('session_version')

    # ### end Alembic commands ###
