"""org_invite_tracking

Revision ID: e80ea29bf39b
Revises: a8c1d2e3f4b5
Create Date: 2025-12-26 19:43:04.043833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80ea29bf39b'
down_revision = 'a8c1d2e3f4b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invited_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('invited_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invite_last_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('invite_send_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('invite_accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('invite_revoked_at', sa.DateTime(), nullable=True))

    # Drop the server default after backfilling existing rows.
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.alter_column('invite_send_count', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.drop_column('invite_revoked_at')
        batch_op.drop_column('invite_accepted_at')
        batch_op.drop_column('invite_send_count')
        batch_op.drop_column('invite_last_sent_at')
        batch_op.drop_column('invited_by_user_id')
        batch_op.drop_column('invited_at')

    # ### end Alembic commands ###
