"""email verification

Revision ID: e947b7b2fb8c
Revises: cdb2afe02d62
Create Date: 2025-12-22 16:01:57.820524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e947b7b2fb8c'
down_revision = 'cdb2afe02d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false()))

    # Treat pre-existing accounts as verified to avoid lockouts after deployment.
    # Use a real boolean literal for Postgres compatibility (SQLite also accepts TRUE).
    op.execute(sa.text('UPDATE users SET email_verified = TRUE'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
